#!/usr/bin/env python3
"""
JARVIS-AI Configuration Setup Script
=====================================
Run this script to create your config.yaml file with API keys.
This is the ONLY setup step you need after pulling from GitHub.

Usage:
    python3 setup_config.py
"""

import os
import sys

CONFIG_TEMPLATE = """# JARVIS-AI Configuration
# Generated by setup_config.py

camera:
  device_index: 0
  fps: 30

face_recognition:
  model: "hog"
  tolerance: 0.6
  greeting_cooldown_seconds: 300
  known_faces_dir: "known_faces"

gesture:
  hold_duration_seconds: 0.5
  confidence_threshold: 0.8
  max_num_hands: 1

voice:
  wake_word: "jarvis"
  listen_timeout: 10
  phrase_limit: 10
  recognizer_engine: "google"

tts:
  engine: "pyttsx3"
  rate: 180
  volume: 1.0

dashboard:
  type: "tkinter"
  refresh_interval_seconds: 30

data:
  news_api_key: "{news_api_key}"
  stock_symbols:
    - "AAPL"
    - "GOOGL"
    - "MSFT"
    - "AMZN"
    - "TSLA"
  project_status_file: "project_status.json"
  cache_duration_minutes: 30

preferences:
  user_name: "{user_name}"
  news_categories:
    - "technology"
    - "business"
    - "science"
  greeting_style: "formal"

# === AI Chat Brain (Gemini - FREE!) ===
ai_chat:
  provider: "gemini"
  gemini_api_key: "{gemini_api_key}"
  gemini_model: "gemini-2.0-flash"
  openai_api_key: ""
  openai_model: "gpt-3.5-turbo"
  groq_api_key: ""
  groq_model: "llama3-8b-8192"
  max_history: 20
  max_tokens: 1000
  temperature: 0.7
  rate_limit_per_minute: 30

reminders:
  data_file: "reminders/reminder_data.json"
  check_interval_seconds: 30
  daily_briefing_time: "08:00"
  sleep_hours_start: 23
  sleep_hours_end: 7
  briefing_enabled: true

smart_home:
  mode: "simulation"
  home_assistant_url: "http://localhost:8123"
  home_assistant_token: ""
  rooms: {{}}

screen_control:
  enabled: true
  safe_mode: true
  mouse_speed: 0.5
  fail_safe: true
  screenshot_dir: "screenshots"

email_calendar:
  email_enabled: false
  calendar_enabled: true
  email:
    provider: "gmail"
    address: ""
    app_password: ""
    imap_server: "imap.gmail.com"
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
  calendar:
    type: "local"
    data_file: "calendar_events.json"
    reminder_minutes_before: 15
    default_event_duration_minutes: 60
"""


def main():
    print("=" * 60)
    print("  JARVIS-AI Configuration Setup")
    print("=" * 60)
    print()
    print("This script will create your config.yaml file.")
    print("You need a Google Gemini API key (it's FREE!).")
    print()
    print("Get your free Gemini API key at:")
    print("  https://aistudio.google.com/apikey")
    print()

    # Check if config.yaml already exists
    config_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config.yaml")
    if os.path.exists(config_path):
        print(f"WARNING: config.yaml already exists at {config_path}")
        answer = input("Overwrite? (y/N): ").strip().lower()
        if answer != "y":
            print("Setup cancelled. Your existing config.yaml is unchanged.")
            return

    # Collect API keys
    print()
    gemini_key = input("Enter your Gemini API key: ").strip()
    if not gemini_key:
        print("WARNING: No Gemini API key provided. JARVIS will run in local mode (limited).")
        print("  You can add it later by editing config.yaml")

    news_key = input("Enter your NewsAPI key (press Enter to skip): ").strip()
    if not news_key:
        print("  (News will use sample data without a NewsAPI key)")

    user_name = input("Enter your name (press Enter for 'User'): ").strip()
    if not user_name:
        user_name = "User"

    # Generate config
    config_content = CONFIG_TEMPLATE.format(
        gemini_api_key=gemini_key,
        news_api_key=news_key,
        user_name=user_name,
    )

    # Write config file
    with open(config_path, "w") as f:
        f.write(config_content)

    print()
    print("=" * 60)
    print("  config.yaml created successfully!")
    print(f"  Location: {config_path}")
    print("=" * 60)
    print()
    print("Next steps:")
    print("  1. Make sure you installed: pip install google-generativeai")
    print("  2. Run JARVIS: python3 main.py")
    print()


if __name__ == "__main__":
    main()
